import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import { ethers } from "ethers";

import styles from "../styles/Home.module.css";
import {
  beer,
  checkIfWalletIsConnected,
  connectWallet,
} from "../utils/helpers";

const Home: NextPage = () => {
  const [currentAccount, setCurrentAccount] = useState("");

  /*
   * This runs our function when the page loads.
   */
  useEffect(() => {
    checkIfWalletIsConnected(setCurrentAccount).catch(console.warn);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <div className="dataContainer">
          <p className="header">👋 Hey there!</p>

          <div className="bio">
            I am farza and I worked on self-driving cars so that's pretty cool
            right? Connect your Ethereum wallet and wave at me!
          </div>

          {!currentAccount && (
            <button
              className="waveButton"
              onClick={() => connectWallet(setCurrentAccount)}
            >
              Connect Wallet
            </button>
          )}

          <button className="waveButton" onClick={beer}>
            Wave at Me
          </button>
        </div>
      </main>
    </div>
  );
};

export default Home;
